config/routes.rb
Rails.application.routes.draw do

  resources :vcenters 

  get "vcenters/:id/:pool_name" => "vcenters#pool", as: :pool

  devise_for :users
  root to: "vcenters#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vcenter.rb
require 'rbvmomi'
  
class Vcenter < ActiveRecord::Base
  validate :url, presence: true, uniqueness: true

  attr_accessor :ram, :storage, :cpu_cores, :cpu_frequency, :pools

  def get_data 
    connect
    set_ram
    set_storage
    set_cpu_cores
    set_cpu_frequency
    set_pools
  end

  def get_pools_data
    connect
    set_pools
  end
  
private 

  def set_ram
    @ram = @vcenter.summary.memory_stats
  end

  def set_storage
    @storage = @vcenter.summary.storage_stats
  end

  def set_cpu_cores
    @cpu_cores = @vcenter.summary.cpu_cores_stats
  end

  def set_cpu_frequency
    @cpu_frequency = @vcenter.summary.cpu_frequency_stats
  end

  def set_pools 
    @pools = @vcenter.host_list
  end

  def connect 
    @vim ||= RbVmomi::VIM.connect(connection_opts)
    @vcenter ||= VSphere::VCenter.new(@vim)
  end

  def connection_opts
   { host: self.url, insecure: true, user: 'svc-vmcreator', password: 'O5ZkSFQ8b8gP' }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/vcenters_controller.rb
class VcentersController < ApplicationController
  before_action :set_vcenter, only: [:show, :edit, :update, :destroy, :pool]

  # GET /vcenters
  # GET /vcenters.json
  def index
    @vcenters = Vcenter.all
  end

  # GET /vcenters/1
  # GET /vcenters/1.json
  def show
    begin 
      @vcenter.get_data
    rescue StandardError => e
      redirect_to vcenters_url, alert: "Got an error: #{e.class}: #{e.message}" 
    end
  end

  # GET /vcenters/new
  def new
    @vcenter = Vcenter.new
  end

  # GET /vcenters/1/edit
  def edit
  end

  # POST /vcenters
  # POST /vcenters.json
  def create
    @vcenter = Vcenter.new(vcenter_params)

    respond_to do |format|
      if @vcenter.save!
        format.html { redirect_to @vcenter, notice: 'Vcenter was successfully created.' }
        format.json { render :show, status: :created, location: @vcenter }
      else
        format.html { render :new }
        format.json { render json: @vcenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vcenters/1
  # PATCH/PUT /vcenters/1.json
  def update
    respond_to do |format|
      if @vcenter.update(vcenter_params)
        format.html { redirect_to @vcenter, notice: 'Vcenter was successfully updated.' }
        format.json { render :show, status: :ok, location: @vcenter }
      else
        format.html { render :edit }
        format.json { render json: @vcenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vcenters/1
  # DELETE /vcenters/1.json
  def destroy
    @vcenter.destroy
    respond_to do |format|
      format.html { redirect_to vcenters_url, notice: 'Vcenter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pool 
    begin 
      @vcenter.get_pools_data
      @pool = @vcenter.pools.detect { |p| p.name == params[:pool_name] }
    rescue StandardError => e
      redirect_to vcenters_url, alert: "Got an error: #{e.class}: #{e.message}" 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vcenter
      @vcenter = Vcenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vcenter_params
      params.require(:vcenter).permit(:url, :pool_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/vcenters_helper.rb
module VcentersHelper
  def properties_need_chart(obj)
    [:ram, :storage, :cpu_cores, :cpu_frequency]
    .select{ |p| !obj.send(p).values.include?(nil) && !obj.send(p).values.include?(0) }
  end

  def col_size(obj)
    12/properties_need_chart(obj).count 
  end

  def data_for_chart(hash)
    hash.delete(:total)
    { "Used #{hash[:used]}" => hash[:used], "Total #{hash[:free]}" => hash[:free] }
  end

  def percent_used(obj, property)
    unless((obj.send(property)[:total].nil?) or (obj.send(property)[:total] == 0) or (obj.send(property)[:used].nil?) or (obj.send(property)[:used] == 0)) 
      (obj.send(property)[:used].to_f / obj.send(property)[:total].to_f * 100).round(1)
    else 
      'N/A'
    end
  end

  def unit_for(property)
    {ram: 'Gbs', storage: 'Gbs', cpu_frequency: 'Mhz', cpu_cores: 'units'}[property]
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ninja Dashboard" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ninja Dashboard" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div id="wrapper">

          <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-cloud"></span> RMS Cloud Dashboard</a>
            </div>

            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul id="active" class="nav navbar-nav side-nav">
                    <li class="selected">
                        <%= link_to vcenters_path do %>
                            <span class="glyphicon glyphicon-cloud"></span> Vcenters
                        <% end %>
                    </li>
                </ul>
                    <div id="page_loading">
                        <div class="col-lg-4">
                            <div class='spinner'>
                                <div class="progress progress-striped active">
                                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="10" style="width: 100%"></div>
                                </div>
                            </div>
                        </div>
                    </div>

            </div>

        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <%= render 'layouts/messages' %>
                </div>
            </div>

            <%= yield %>
        </div>

    </div>
    <!-- /#wrapper -->

  </body>
</html>

app/views/vcenters/_form.html.erb
<%= simple_form_for @vcenter do |f| %>
  <%= f.error_notification %>
    <%= f.input :url, capture: @vcenter.url %>
    <br>
    <%= f.button :submit, class: 'btn btn-success pull-right' %>
<% end %>

app/views/vcenters/edit.html.erb
<div class='row'>
  <div class='col-lg-5'>
    <div class="panel panel-success">
      <div class="panel-heading">
          <h3 class="panel-title"><span class="glyphicon glyphicon-cloud-upload"></span> Add vcenter  </h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <%= link_to vcenters_path, class: 'btn btn-info' do %>
      <span class= "glyphicon glyphicon-arrow-left"> Back</span>
    <% end %>
    <%= link_to @vcenter, class: 'btn btn-info pull-right' do %>
      <span class= "glyphicon glyphicon-arrow-right"> Show</span>
    <% end %>
  </div>
</div>

app/views/vcenters/index.html.erb
<div class="row">
  <div class="col-lg-4">
      <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title"><span class="glyphicon glyphicon-cloud-download"></span> Registered vcenters </h3>
          </div>
          <div class="panel-body">
            <table class='table table-stripped table-hover'>
                <% @vcenters.each do |vcenter| %>
                  <tr>
                    <td><%= link_to vcenter.url, vcenter %></td>
                    <td>
                      <%= link_to edit_vcenter_path(vcenter) do %>
                          <span class="glyphicon glyphicon-cog">
                      <%end%>
                      <%= link_to vcenter, method: :delete, data: { confirm: 'Are you sure?' } do %>
                          <span class="glyphicon glyphicon-remove">
                      <%end%>
                    </td>
                <% end %>
                <tr>
                  <td>
                    <%= link_to new_vcenter_path do %>
                      <span class="glyphicon glyphicon-plus"></span> Add
                    <% end %>
                  </td>
                  <td></td>
                </tr>
            </table>
          <div>
      </div>
  </div>
</div>

app/views/vcenters/new.html.erb
<div class='row'>
  <div class='col-lg-5'>
    <div class="panel panel-success">
      <div class="panel-heading">
          <h3 class="panel-title"><span class="glyphicon glyphicon-cloud-upload"></span> Add vcenter  </h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
    <%= link_to vcenters_path, class: 'btn btn-info' do %>
      <span class= "glyphicon glyphicon-arrow-left"> Back</span>
    <% end %>
  </div>
</div>

app/views/vcenters/pool.html.erb
<title><%= @pool.name %></title>

<ol class="breadcrumb">
  <li><%= link_to @vcenter.url, @vcenter %></li>
  <li class="active"><%= @pool.name %></li>
</ol>

<div class="row">
    <div class="col-lg-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-th-list"></span> Hardware values </h3>
            </div>
            <div class="panel-body">
              <table class= "table table-stripped table-hover">
              <thead>
                <td>
                  Attribute
                </td>
                <td>
                  Total
                </td>
                <td>
                  Used
                </td>
                <td>
                  Free
                </td>
                <td>
                  Percent used
                </td>
              </thead>
                <tbody>
                  <% [:ram, :storage, :cpu_cores, :cpu_frequency].each do |property| %>
                    <tr>
                      <td>
                        <%= property.to_s.humanize %> <%= unit_for(property) %>
                      </td>
                      <td>
                        <%= @pool.send(property)[:total] || "N/A" %>
                      </td>
                      <td>
                        <%= @pool.send(property)[:used] || "N/A" %>
                      </td>
                      <td>
                        <%= @pool.send(property)[:free] || "N/A" %>
                      </td>
                      <td>
                        <%= percent_used(@pool, property)%>
                      </td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
  <% properties_need_chart(@pool).each do |property| %>
      <div class="col-lg-<%= col_size(@pool) %>">
          <div class="panel panel-primary">
              <div class="panel-heading">
                  <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> <%= property.to_s.humanize %></h3>
              </div>
              <div class="panel-body">
                  <%= pie_chart data_for_chart(@pool.send(property)), library: { backgroundColor: "#333" , legend: { textStyle: { color: 'white' } } } %>
              </div>
          </div>
      </div>
  <% end %>
</div>

<%= link_to vcenter_path(@vcenter), class: 'btn btn-info' do %>
  <span class= "glyphicon glyphicon-arrow-left"></span> Back to <%= @vcenter.url %>
<% end %>

app/views/vcenters/show.html.erb
<title><%= @vcenter.url %></title>

<div class="row">
    <div class="col-lg-12">
        <%= render 'layouts/messages' %>
    </div>
</div>
  <h2><%= @vcenter.url%></h2>
<div class="row">
    <div class="col-lg-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-cloud-download"></span> Hardware values </h3>
            </div>
            <div class="panel-body">
              <table class= "table table-stripped table-hover">
              <thead>
                <td>
                  Attribute
                </td>
                <td>
                  Total
                </td>
                <td>
                  Used
                </td>
                <td>
                  Free
                </td>
                <td>
                  Percent used
                </td>
              </thead>
              <tbody>
                <% [:ram, :storage, :cpu_cores, :cpu_frequency].each do |property| %>
                <tr>
                  <td>
                    <%= property.to_s.humanize %> (<%= unit_for(property) %>)
                  </td>
                  <td>
                    <%= @vcenter.send(property)[:total] || "N/A" %>
                  </td>
                  <td>
                    <%= @vcenter.send(property)[:used] || "N/A" %>
                  </td>
                  <td>
                    <%= @vcenter.send(property)[:free] || "N/A" %>
                  </td>
                  <td>
                    <%= percent_used(@vcenter, property)%>
                  </td>
                </tr>
                <%end%>
              </tbody>
              </table>
            </div>
        </div>
    </div>


     <div class="col-lg-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-folder-open"> Clusters </h3>
            </div>
            <div class="panel-body">
              <table class="table table-stripped table-hover">
                <tbody>
                  <% @vcenter.pools.each do |pool| %>
                    <tr>
                      <td>
                        <%= link_to pool.name, {controller: 'vcenters', action: 'pool', pool_name: pool.name} %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
  <% properties_need_chart(@vcenter).each do |property| %>
      <div class="col-lg-<%= col_size(@vcenter) %>">
          <div class="panel panel-primary">
              <div class="panel-heading">
                  <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> <%= property.to_s.humanize %>/<%= unit_for(property) %> </h3>
              </div>
              <div class="panel-body">
                  <%= pie_chart data_for_chart(@vcenter.send(property)), library: {backgroundColor: "#333" , legend: { textStyle: { color: 'white' } } } %>
              </div>
          </div>
      </div>
  <% end %>
</div>

<%= link_to vcenters_path, class: 'btn btn-info' do %>
  <span class= "glyphicon glyphicon-arrow-left"> Vcenters</span>
<% end %>